# -*- coding: utf-8 -*-
"""Next Word Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eeUhBt8oen9JRynrddyqBbrtVg2HLKcJ
"""

book_description = """Shadow Life: A Portrait of Anne Frank and Her Family by Barry Denenberg offers a comprehensive and insightful look into the lives of Anne Frank and her family,
 extending beyond the confines of the Secret Annex where they hid during World War II. It delves into their experiences before, during, and after the war, painting a more complete
  picture of their lives. The book is divided into four sections: Living: This section explores the Frank family life in Frankfurt before the rise of Nazism and their subsequent move
   to Amsterdam. It details their early years, personalities, and the growing threat of persecution that led them to seek refuge in the Netherlands. Hiding: This section focuses on
    the two years the Frank family spent in hiding in the Secret Annex. Denenberg not only recounts Anne's experiences, which are well-known from her diary, but also delves into th
    e perspectives of the other seven people hiding with them. He explores their relationships, struggles, fears, and hopes during this period of confinement and uncertainty.
     Dying: This section details the tragic events that followed the discovery of the Secret Annex. It recounts the capture and deportation of the Frank family and the Van Pels
      family, their experiences in Auschwitz and other concentration camps, and the ultimate deaths of Anne and Margot Frank in Bergen-Belsen. Surviving: This section focuses
       on Otto Frank, Anne's father, and the only one of the eight people in hiding to survive the Holocaust. It details his return to Amsterdam, the discovery of Anne's diary,
       and his efforts to publish it and share her story with the world. Denenberg's meticulous research, drawing on a variety of sources including diaries, letters, and interviews
       , allows him to create a richly detailed and nuanced portrait of the Frank family. He humanizes them, revealing their flaws and complexities alongside their strengths and
        resilience. He also provides a broader historical context, highlighting the experiences of other Jews during the Holocaust and the impact of the war on the world. One of the
         unique aspects of Shadow Life is its focus on Margot Frank, Anne's older sister. While Anne's diary provides a vivid account of her own experiences, Margot's perspective
         remains largely unknown as her diary was never found. Denenberg attempts to fill this gap by imagining what Margot might have written, based on her personality and the limited
         information available about her. This adds another layer of depth and complexity to the story, shedding light on the dynamics between the two sisters and their individual struggles.
          The book does not shy away from the harsh realities of the Holocaust, detailing the horrors and atrocities faced by the Frank family and millions of other Jews. However,
           it also celebrates their courage, resilience, and unwavering hope in the face of unimaginable suffering. It is a testament to the enduring power of the human spirit
            and the importance of remembering the past in order to prevent future tragedies. In summary, Shadow Life is a powerful and moving account of the Frank family's
            life before, during, and after the Holocaust. It is a story of love, loss, resilience, and the enduring power of the human spirit. It is a book that challenges
            readers to confront the darkest chapters of history and to reflect on the importance of empathy, compassion, and the fight for justice.

The vibe of Shadow Life is akin to stepping into a time capsule,
 transporting you to the bustling streets of pre-war Frankfurt
 and the hushed attic of the Secret Annex. The pages echo with the laughter of children playing, the whispers
  of secrets shared, and the quiet scratching of a pen documenting dreams and fears. Imagine faded photographs coming to life, revealing the faces of a family forever etched
  in history. Their smiles are tinged with an underlying sadness, their eyes reflecting both the innocence of youth and the weight of the world. The book's vibe is a poignant
  blend of warmth and sorrow, resilience and despair. It evokes a sense of shared humanity, reminding us that even in the darkest of times, hope can flicker and the human spirit
   can endure. As you turn the pages, you'll feel the weight of the past pressing upon the present, the echoes of history resonating with contemporary concerns. The book's vibe is
    a stark reminder of the fragility of life and the importance of cherishing every moment, every memory. The lingering vibe of Shadow Life is a profound sense of reflection,
    leaving you pondering the complexities of human nature, the devastating consequences of hate, and the enduring power of love and hope. It's a book that stays with you long
    after you've closed its pages, its echoes reverberating in your thoughts and dreams."""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

tokenizer.fit_on_texts([book_description])

len(tokenizer.word_index)

tokenizer.word_index

input_sequences=[]
for sentence in book_description.split('.'):
    sequence=tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1,len(sequence)):
        input_sequences.append(sequence[:i+1])

input_sequences

max_len=max([len(x) for x in input_sequences])

max_len

from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

padded_sequences

X=padded_sequences[:,:-1]
y=padded_sequences[:,-1]

X.shape

y.shape

from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)

from tensorflow import keras
from keras.layers import Embedding,LSTM,Dense
model=keras.Sequential()
model.add(Embedding(len(tokenizer.word_index)+1,100,input_length=max_len-1))
model.add(LSTM(100))
model.add(Dense(len(tokenizer.word_index)+1,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

model.fit(X,y,epochs=100)

import numpy as np
Input="This book explores"
for i in range(30):
  Input_seq=tokenizer.texts_to_sequences([Input])[0]
  Input_seq=pad_sequences([Input_seq],maxlen=max_len-1,padding='pre')
  ans=model.predict(Input_seq)
  ans=tokenizer.index_word[np.argmax(ans)]
  Input=Input+" "+ans

print(Input)

model.save("Next_Word_Predictor.h5")

